spring:
    application:
        name: TaskManager
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:taskmanager
        username: root
        #http://localhost:8080/h2-console
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
